import { useEffect, useRef, useState, type ReactNode } from 'react'
import { api } from '../api/client'
import { useLanguage } from '../shared/LanguageContext'

type Section='audience'|'articles'|'volumes'|'users'|'reviewers'|'authors'|'editors'|'workflow'
type Dashboard={period_days:number;date_from:string;date_to:string;summary:{page_views:number;views:number;unique_visitors:number;reads:number;downloads:number;read_rate:number};trend:{date:string;views:number;page_views:number;downloads:number}[];top_articles:{article_id:number;title:string;views:number;reads:number;downloads:number;unique_visitors:number;read_rate:number}[];top_volumes:{volume_id:number;views:number;reads:number;downloads:number;unique_visitors:number}[];top_pages:{path:string;views:number;unique_visitors:number}[]}
type User={id:number;full_name?:string;first_name?:string;last_name?:string;email:string;role:string;roles?:string[];is_active:boolean;organization?:string;institution?:string;preferred_language?:string;orcid?:string;reviewer_science_fields?:string[];is_council_member?:boolean;is_collegium_member?:boolean;notify_status?:boolean;accept_terms?:boolean}
type Author={id:number;first_name:string;last_name:string;is_corresponding?:boolean;orcid?:string;scopus_author_id?:string;researcher_id?:string;country?:{name?:string}}
const keys:Section[]=['audience','articles','volumes','users','reviewers','authors','editors','workflow']
const today=()=>new Date().toISOString().slice(0,10), ago=(n:number)=>{const d=new Date();d.setDate(d.getDate()-n+1);return d.toISOString().slice(0,10)}
const empty:Dashboard={period_days:30,date_from:ago(30),date_to:today(),summary:{page_views:0,views:0,unique_visitors:0,reads:0,downloads:0,read_rate:0},trend:[],top_articles:[],top_volumes:[],top_pages:[]}
const has=(u:User,r:string)=>u.role===r||u.roles?.includes(r), name=(u:User)=>u.full_name||[u.first_name,u.last_name].filter(Boolean).join(' ')||u.email
const counts=<T,>(a:T[],fn:(x:T)=>string)=>a.reduce<Record<string,number>>((o,x)=>{const k=fn(x)||'Не указано';o[k]=(o[k]||0)+1;return o},{})
const sorted=(o:Record<string,number>)=>Object.entries(o).sort((a,b)=>b[1]-a[1]) as [string,number][]
const text={
 ru:{title:'Аналитика',sub:'Ключевые показатели журнала в одном месте',catalog:'Разделы аналитики',hint:'Выберите направление, чтобы открыть подробный отчёт.',open:'Открыть отчёт',back:'Все разделы',items:{audience:['Посещаемость','Аудитория сайта и популярные страницы'],articles:['Статьи','Чтения, скачивания и спрос на публикации'],volumes:['Выпуски','Популярность номеров журнала'],users:['Пользователи','Активность и распределение по ролям'],reviewers:['Рецензенты','Состав, специализации и профили'],authors:['Авторы','География и научные профили'],editors:['Редакторы','Состав редакции и активность'],workflow:['Редакционный процесс','Готовность команды и точки внимания']}},
 en:{title:'Analytics',sub:'Key journal indicators in one place',catalog:'Analytics sections',hint:'Select a section to open a detailed report.',open:'Open report',back:'All sections',items:{audience:['Traffic','Website audience and popular pages'],articles:['Articles','Reads, downloads and publication demand'],volumes:['Issues','Journal issue popularity'],users:['Users','Activity and role distribution'],reviewers:['Reviewers','Team, expertise and profiles'],authors:['Authors','Geography and research profiles'],editors:['Editors','Editorial team and activity'],workflow:['Editorial workflow','Team readiness and attention points']}},
 kz:{title:'Аналитика',sub:'Журналдың негізгі көрсеткіштері бір жерде',catalog:'Аналитика бөлімдері',hint:'Толық есепті ашу үшін бағытты таңдаңыз.',open:'Есепті ашу',back:'Барлық бөлімдер',items:{audience:['Кіру статистикасы','Сайт аудиториясы және танымал беттер'],articles:['Мақалалар','Оқылымдар мен жүктеулер'],volumes:['Шығарылымдар','Журнал нөмірлерінің танымалдығы'],users:['Пайдаланушылар','Белсенділік және рөлдер'],reviewers:['Рецензенттер','Құрам, бағыттар және профильдер'],authors:['Авторлар','География және ғылыми профильдер'],editors:['Редакторлар','Редакция құрамы мен белсенділігі'],workflow:['Редакциялық процесс','Команда дайындығы мен бақылау']}}
} as const

export default function AdminAnalyticsPage(){
 const {lang}=useLanguage(),t=text[lang];const q=new URLSearchParams(location.search).get('section');const [section,setSection]=useState<Section|null>(keys.includes(q as Section)?q as Section:null)
 const [range,setRange]=useState({from:ago(30),to:today()}),[applied,setApplied]=useState(range),[data,setData]=useState(empty),[users,setUsers]=useState<User[]>([]),[authors,setAuthors]=useState<Author[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false),restored=useRef(false)
 useEffect(()=>{let active=true;setLoading(true);Promise.allSettled([api.getAnalyticsDashboard<Dashboard>({date_from:applied.from,date_to:applied.to,limit:20}),api.getAdminUsers<User[]>(),api.getAuthors<Author[]>()]).then(r=>{if(!active)return;if(r[0].status==='fulfilled')setData(r[0].value);if(r[1].status==='fulfilled')setUsers(r[1].value);if(r[2].status==='fulfilled')setAuthors(r[2].value);setError(r.some(x=>x.status==='rejected'))}).finally(()=>active&&setLoading(false));return()=>{active=false}},[applied])
 useEffect(()=>{if(loading||restored.current)return;restored.current=true;const y=Number(sessionStorage.getItem('analytics-scroll')||0);requestAnimationFrame(()=>scrollTo(0,y))},[loading])
 useEffect(()=>{const save=()=>sessionStorage.setItem('analytics-scroll',String(scrollY));addEventListener('scroll',save,{passive:true});return()=>{save();removeEventListener('scroll',save)}},[])
 const open=(s:Section|null)=>{setSection(s);const u=new URL(location.href);s?u.searchParams.set('section',s):u.searchParams.delete('section');history.replaceState({},'',u.pathname+u.search);scrollTo({top:0,behavior:'smooth'})}
 return <div className="analytics-page"><header className="analytics-hero"><div className="analytics-hero__content"><Icon n="chart"/><div><p className="eyebrow">ADMIN / INSIGHTS</p><h1>{t.title}</h1><p>{t.sub}</p></div></div></header>{!section?<><div className="analytics-directory__heading"><div><h2>{t.catalog}</h2><p>{t.hint}</p></div><span>8</span></div><section className="analytics-directory">{keys.map(k=><button className={`analytics-section-card analytics-section-card--${k}`} onClick={()=>open(k)} key={k}><span className="analytics-section-card__icon"><Icon n={k}/></span><span className="analytics-section-card__copy"><strong>{t.items[k][0]}</strong><small>{t.items[k][1]}</small></span><span className="analytics-section-card__action">{t.open} →</span></button>)}</section></>:<><div className="analytics-detail-head"><button className="analytics-back" onClick={()=>open(null)}>← {t.back}</button><span className={`analytics-detail-head__icon analytics-section-card--${section}`}><Icon n={section}/></span><div><h2>{t.items[section][0]}</h2><p>{t.items[section][1]}</p></div></div>{(['audience','articles','volumes'] as Section[]).includes(section)&&<Filter range={range} setRange={setRange} apply={()=>setApplied(range)}/>} {error&&<div className="alert error">Не удалось загрузить часть аналитики</div>}{loading?<div className="loading">Загружаем аналитику…</div>:<Detail section={section} d={data} users={users} authors={authors}/>}</>}</div>
}

function Detail({section,d,users,authors}:{section:Section;d:Dashboard;users:User[];authors:Author[]}){const rev=users.filter(x=>has(x,'reviewer')),ed=users.filter(x=>has(x,'editor'));const roles:Record<string,string>={author:'Авторы',reviewer:'Рецензенты',editor:'Редакторы',layout:'Верстальщики',admin:'Администраторы'}
 if(section==='audience')return <><Stats a={[['Просмотры страниц',d.summary.page_views],['Посетители',d.summary.unique_visitors],['Просмотры статей',d.summary.views]]}/><Trend d={d} metric="page_views"/><Table title="Популярные страницы" heads={['Страница','Просмотры','Посетители']} rows={d.top_pages.map(x=>[x.path,x.views,x.unique_visitors])}/></>
 if(section==='articles')return <><Stats a={[['Просмотры',d.summary.views],['Дочитывания',d.summary.reads],['Скачивания PDF',d.summary.downloads],['Доля дочитываний',d.summary.read_rate+'%']]}/><Trend d={d} metric="views"/><Table title="Самые читаемые статьи" heads={['Статья','Просмотры','Посетители','Дочитывания','PDF']} rows={d.top_articles.map(x=>[x.title,x.views,x.unique_visitors,x.reads,x.downloads])}/></>
 if(section==='volumes')return <><Stats a={[['Просмотры',d.summary.views],['Посетители',d.summary.unique_visitors],['PDF',d.summary.downloads]]}/><Trend d={d} metric="downloads"/><Table title="Популярные выпуски" heads={['Выпуск','Просмотры','Посетители','PDF']} rows={d.top_volumes.map(x=>['№ '+x.volume_id,x.views,x.unique_visitors,x.downloads])}/></>
 if(section==='users')return <><Stats a={[['Всего',users.length],['Активные',users.filter(x=>x.is_active).length],['Неактивные',users.filter(x=>!x.is_active).length],['С организацией',users.filter(x=>x.organization||x.institution).length]]}/><Dist title="Распределение по ролям" rows={sorted(counts(users,x=>roles[x.role]||x.role))} total={users.length}/><Attention users={users}/></>
 if(section==='reviewers')return <><Stats a={[['Всего рецензентов',rev.length],['Активные',rev.filter(x=>x.is_active).length],['Со специализацией',rev.filter(x=>x.reviewer_science_fields?.length).length],['С ORCID',rev.filter(x=>x.orcid).length]]}/><div className="analytics-split"><Dist title="Научные направления" rows={sorted(counts(rev.flatMap(x=>x.reviewer_science_fields||[]),x=>x))} total={rev.length}/><Dist title="Языки" rows={sorted(counts(rev,x=>x.preferred_language||'Не указан'))} total={rev.length}/></div><Attention users={rev}/></>
 if(section==='authors')return <><Stats a={[['Всего авторов',authors.length],['Для переписки',authors.filter(x=>x.is_corresponding).length],['С ORCID',authors.filter(x=>x.orcid).length],['С Scopus ID',authors.filter(x=>x.scopus_author_id).length]]}/><Dist title="География авторов" rows={sorted(counts(authors,x=>x.country?.name||'Не указана'))} total={authors.length}/><Table title="Научные профили" heads={['Автор','Страна','ORCID','Scopus ID']} rows={authors.map(x=>[`${x.first_name} ${x.last_name}`,x.country?.name||'—',x.orcid||'—',x.scopus_author_id||'—'])}/></>
 if(section==='editors')return <><Stats a={[['Всего редакторов',ed.length],['Активные',ed.filter(x=>x.is_active).length],['Члены совета',ed.filter(x=>x.is_council_member).length],['Редколлегия',ed.filter(x=>x.is_collegium_member).length]]}/><Dist title="Организации" rows={sorted(counts(ed,x=>x.organization||x.institution||'Не указана'))} total={ed.length}/><Table title="Состав редакции" heads={['Редактор','Организация','Статус']} rows={ed.map(x=>[name(x),x.organization||x.institution||'—',x.is_active?'Активен':'Неактивен'])}/></>
 const ready=users.filter(x=>x.is_active&&(x.organization||x.institution)).length;return <><Stats a={[['Готовность профилей',users.length?Math.round(ready*100/users.length)+'%':'0%'],['Ожидают активации',users.filter(x=>!x.is_active).length],['Получают уведомления',users.filter(x=>x.notify_status).length],['Приняли условия',users.filter(x=>x.accept_terms).length]]}/><section className="panel analytics-insight"><Icon n="workflow"/><div><h3>Контроль качества данных</h3><p>В приоритете — активация команды, заполнение организаций и научных профилей.</p></div></section><Attention users={users}/></>}

function Filter({range,setRange,apply}:{range:{from:string;to:string};setRange:(x:{from:string;to:string})=>void;apply:()=>void}){return <section className="analytics-filter panel"><div className="analytics-quick-periods">{[7,30,90,365].map(n=><button key={n} onClick={()=>{const x={from:ago(n),to:today()};setRange(x)}}>{n===365?'1 год':n+' дней'}</button>)}</div><label>С<input type="date" value={range.from} onChange={e=>setRange({...range,from:e.target.value})}/></label><label>По<input type="date" value={range.to} onChange={e=>setRange({...range,to:e.target.value})}/></label><button className="button button--primary" onClick={apply}>Применить</button></section>}
const Stats=({a}:{a:[string,string|number][]})=><section className="analytics-cards">{a.map(x=><div className="analytics-card" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</section>
function Trend({d,metric}:{d:Dashboard;metric:'views'|'page_views'|'downloads'}){const max=Math.max(1,...d.trend.map(x=>x[metric]));return <section className="panel analytics-panel"><div className="analytics-panel__heading"><h2>Динамика</h2><span>{d.period_days} дн.</span></div><div className="analytics-chart">{d.trend.map(x=><div className="analytics-bar-wrap" key={x.date} title={`${x.date}: ${x[metric]}`}><div className="analytics-bar" style={{height:Math.max(2,x[metric]/max*100)+'%'}}/><small>{x.date.slice(5)}</small></div>)}</div></section>}
function Dist({title,rows,total}:{title:string;rows:[string,number][];total:number}){return <section className="panel analytics-panel analytics-distribution"><h2>{title}</h2>{rows.map(x=><div className="analytics-distribution__row" key={x[0]}><div><span>{x[0]}</span><strong>{x[1]}</strong></div><div className="analytics-distribution__track"><i style={{width:Math.max(3,x[1]*100/Math.max(total,1))+'%'}}/></div></div>)}</section>}
function Table({title,heads,rows}:{title:string;heads:string[];rows:(string|number)[][]}){return <section className="panel analytics-panel"><h2>{title}</h2>{!rows.length?<div className="table__empty">Нет данных</div>:<div className="analytics-table-wrap"><table className="analytics-table"><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.slice(0,30).map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{j?x:<strong>{x}</strong>}</td>)}</tr>)}</tbody></table></div>}</section>}
const Attention=({users}:{users:User[]})=><Table title="Требует внимания" heads={['Пользователь','Роль','Рекомендация']} rows={users.filter(x=>!x.is_active||!x.organization||(has(x,'reviewer')&&!x.reviewer_science_fields?.length)).map(x=>[name(x),x.role,!x.is_active?'Активировать аккаунт':has(x,'reviewer')&&!x.reviewer_science_fields?.length?'Заполнить специализацию':'Указать организацию'])}/>
function Icon({n}:{n:Section|'chart'}):ReactNode{const p:Record<string,string>={chart:'M4 19V9m6 10V5m6 14v-7m6 7V2M3 6l6-3 6 5 7-6',audience:'M2 12s4-6 10-6 10 6 10 6-4 6-10 6S2 12 2 12Zm10-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4',articles:'M6 3h9l4 4v14H6V3Zm8 0v5h5M9 12h7m-7 4h7',volumes:'M4 6a3 3 0 0 1 3-3h13v16H7a3 3 0 0 0-3 3V6Zm4 1h8',users:'M9 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM3 20a6 6 0 0 1 12 0m1-14a3 3 0 0 1 0 5m1 3a5 5 0 0 1 4 5',reviewers:'M8 6h8m-7-3h6l1 3h3v15H5V6h3Zm0 8 2 2 5-5',authors:'m4 20 4-1L19 8a2 2 0 0 0-3-3L5 16l-1 4Zm10-13 3 3M4 20h16',editors:'M9 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM3 20a6 6 0 0 1 10-5m4-2v8m-4-4h8',workflow:'M3 3h6v6H3V3Zm12 12h6v6h-6v-6ZM9 6h4a4 4 0 0 1 4 4v5m-2 3h-4a4 4 0 0 1-4-4V9'};return <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={p[n]}/></svg>}
